#!/bin/sh
# ============================================
# luci-app-picoclaw APK Builder for OpenWrt 25.xx
# Run this script ON your OpenWrt 25.x router
# ============================================
#
# Usage:
#   chmod +x build-apk.sh
#   ./build-apk.sh
#
# Output: luci-app-picoclaw_25.xx_all.apk

set -e

PKG_NAME="luci-app-picoclaw"
PKG_VERSION="1.1.5"
PKG_DESC="LuCI management interface for PicoClaw AI assistant"
PKG_MAINTAINER="GennKann"
PKG_ARCH="all"
OUTPUT_FILE="${PKG_NAME}_${PKG_VERSION}_${PKG_ARCH}.apk"
BUILD_DIR="/tmp/${PKG_NAME}-build"

echo "=== Building ${PKG_NAME} APK for OpenWrt 25.xx ==="
echo ""

# Check if running on OpenWrt 25 with apk
if command -v apk >/dev/null 2>&1; then
    echo "[OK] apk-tools found"
    PKG_MANAGER="apk"
elif command -v opkg >/dev/null 2>&1; then
    echo "[WARN] opkg detected. This script is for OpenWrt 25+ (apk)."
    echo "       Use the IPK package or install script for OpenWrt 24.10."
    exit 1
else
    echo "[ERROR] Neither apk nor opkg found. Are you on OpenWrt?"
    exit 1
fi

# Clean up
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}/pkg"

# --- Install files ---
echo "[1/5] Installing files..."

# LuCI Controller — copy from repo source
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
mkdir -p "${BUILD_DIR}/pkg/usr/lib/lua/luci/controller"
if [ -f "${REPO_DIR}/luci/controller/picoclaw.lua" ]; then
    cp "${REPO_DIR}/luci/controller/picoclaw.lua" "${BUILD_DIR}/pkg/usr/lib/lua/luci/controller/picoclaw.lua"
    echo "  -> controller/picoclaw.lua (copied from repo)"
else
    echo "  [WARN] luci/controller/picoclaw.lua not found, skipping"
fi

# LuCI View Template — copy from repo source
mkdir -p "${BUILD_DIR}/pkg/usr/lib/lua/luci/view/picoclaw"
if [ -f "${REPO_DIR}/luci/view/picoclaw/main.htm" ]; then
    cp "${REPO_DIR}/luci/view/picoclaw/main.htm" "${BUILD_DIR}/pkg/usr/lib/lua/luci/view/picoclaw/main.htm"
    echo "  -> view/picoclaw/main.htm (copied from repo)"
else
    echo "  [WARN] luci/view/picoclaw/main.htm not found, skipping"
fi

# init.d service script
mkdir -p "${BUILD_DIR}/pkg/etc/init.d"
cat > "${BUILD_DIR}/pkg/etc/init.d/picoclaw" << 'INITD'
#!/bin/sh /etc/rc.common
START=99
STOP=90

USE_PROCD=1

start_service() {
    procd_open_instance picoclaw
    procd_set_param command /usr/bin/picoclaw gateway
    procd_set_param env HOME=/root
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root
    procd_close_instance
}

stop_service() {
    killall picoclaw 2>/dev/null
}

service_triggers() {
    procd_add_reload_trigger "picoclaw"
}
INITD
chmod 755 "${BUILD_DIR}/pkg/etc/init.d/picoclaw"
echo "  -> etc/init.d/picoclaw"

# --- Build APK package ---
echo "[2/5] Building APK package..."

# Use apk-tools to create the package
# APK package format for OpenWrt 25 uses the apk-tools mkpkg command
cd "${BUILD_DIR}"

# Create the APK package using apk-tools
# The .PKGINFO file contains package metadata
mkdir -p pkg/.PKGINFO
cat > pkg/.PKGINFO/pkginfo << PKGINFO
# Generated by luci-app-picoclaw build script
pkgname = ${PKG_NAME}
pkgver = ${PKG_VERSION}
pkgdesc = ${PKG_DESC}
url = https://github.com/sipeed/picoclaw
builddate = $(date +%s)
packager = ${PKG_MAINTAINER}
size = $(du -sb pkg | cut -f1)
arch = ${PKG_ARCH}
origin = ${PKG_NAME}
license = MIT
depend = luci
depend = picoclaw
datahash = $(find pkg -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
PKGINFO
echo "  -> .PKGINFO/pkginfo"

# Try to use apk-tools mkpkg if available
if command -v apk >/dev/null 2>&1; then
    if apk mkpkg --help >/dev/null 2>&1; then
        echo "[3/5] Using apk mkpkg..."
        cd "${BUILD_DIR}/pkg"
        apk mkpkg -o "/tmp/${OUTPUT_FILE}" 2>/dev/null || true
        if [ -f "/tmp/${OUTPUT_FILE}" ]; then
            echo "[4/5] APK created successfully!"
            cp "/tmp/${OUTPUT_FILE}" "/root/${OUTPUT_FILE}" 2>/dev/null || \
            cp "/tmp/${OUTPUT_FILE}" "$(pwd)/${OUTPUT_FILE}"
            echo "[5/5] Package saved to: /root/${OUTPUT_FILE}"
            echo ""
            echo "Install with:"
            echo "  apk add --allow-untrusted /root/${OUTPUT_FILE}"
            rm -rf "${BUILD_DIR}"
            exit 0
        fi
    fi
fi

# Fallback: create a simple tar.gz based APK (compatible structure)
echo "[3/5] Using fallback tar-based APK build..."
cd "${BUILD_DIR}"
tar czf "/tmp/${OUTPUT_FILE}" -C pkg .
if [ -f "/tmp/${OUTPUT_FILE}" ]; then
    echo "[4/5] Package archive created!"
    
    # Copy to accessible location
    cp "/tmp/${OUTPUT_FILE}" "/root/${OUTPUT_FILE}" 2>/dev/null || \
    cp "/tmp/${OUTPUT_FILE}" "$(pwd)/${OUTPUT_FILE}"
    
    echo "[5/5] Package saved!"
    echo ""
    echo "=== Build Complete ==="
    echo "File: /root/${OUTPUT_FILE}"
    echo ""
    echo "Install on this router:"
    echo "  apk add --allow-untrusted /root/${OUTPUT_FILE}"
    echo ""
    echo "Or copy to another router and install:"
    echo "  scp /root/${OUTPUT_FILE} root@<router-ip>:/tmp/"
    echo "  ssh root@<router-ip> 'apk add --allow-untrusted /tmp/${OUTPUT_FILE}'"
else
    echo "[ERROR] Failed to create package!"
    exit 1
fi

# Cleanup
rm -rf "${BUILD_DIR}"
